In [3]:
import pandas as pd

In [69]:
filename = "SZAKVKODOK.xlsx"
df = pd.read_excel(f"forras/excel/{filename}")
df

        ID    KOD                                      LEIRAS  MEGFELEL
0        1      0                             Megkötés nélkül       NaN
1    54215    131           Anaesthesiológia-intenzív terápia       NaN
2    54216    208                   Arc-állcsont-szájsebészet       NaN
3    54217    134                               Belgyógyászat       NaN
4    54218    135                               Bőrgyógyászat       NaN
..     ...    ...                                         ...       ...
147  75438   1094  Tüdőbetegségek és gümőkóros megbetegedések      53.0
148  75439    248                                Tüdősebészet      27.0
149  75440     55                                Üzemorvostan    1073.0
150  75441   1063                                  higiénikus       NaN
151  86313  10042                    Gyermek hemato-onkológia       NaN

[152 rows x 4 columns]

In [70]:
df.to_csv(f"forras/csv/{filename.strip('xlsl')}csv", sep=';',index=False)

Cleaning

In [122]:
filename = "GYOGYSZ.csv"
df = pd.read_csv(f"forras/csv/{filename}", sep=';')
df

C:\Users\kornel.gatmezei_hifl\AppData\Local\Temp\ipykernel_668\2684659877.py:2: DtypeWarning: Columns (19,38,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"forras/csv/{filename}", sep=';')

,ID,KOZHID,OEP_DAT,SWITCH,TIPUS,OEP_TTT,OEP_EAN,OEP_TK,TKTORLES,TKTORLESDAT,...,FORGENGT_ID,FORGALMAZ,FORGALMAZ_ID,BRANDNEV,BRAND_ID,KERESZTJELZES,REGI_NEV,PRAS_TERMEK,NICHE_ID,KEST_TERM
0,61808708,9708,20240301,M,A,110001431,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
1,61808710,10206,20240301,M,F,110004691,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
2,61808711,10262,20240301,M,A,110005451,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
3,61808712,10264,20240301,M,A,110005477,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
4,61808713,10265,20240301,M,A,110005485,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,61809499,12089,20240301,M,K,610000553,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41210,61809500,12088,20240301,M,K,610000561,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41211,61809502,12087,20240301,M,K,610000587,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41212,61809504,12086,20240301,M,K,610000600,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41213,61809524,11855,20240301,M,K,610000618,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0

In [118]:
clean_df = df.dropna(axis=1,how='all')
clean_df

,ID,KOZHID,OEP_DAT,SWITCH,TIPUS,OEP_TTT,OEP_EAN,OEP_TK,TKTORLES,TKTORLESDAT,...,FORGENGT_ID,FORGALMAZ,FORGALMAZ_ID,BRANDNEV,BRAND_ID,KERESZTJELZES,REGI_NEV,PRAS_TERMEK,NICHE_ID,KEST_TERM
0,61808708,9708,20240301,M,A,110001431,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
1,61808710,10206,20240301,M,F,110004691,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
2,61808711,10262,20240301,M,A,110005451,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
3,61808712,10264,20240301,M,A,110005477,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
4,61808713,10265,20240301,M,A,110005485,NaN,Ph. Hg. VIII.,NaN,NaN,...,1.0,Ismeretlen,1,ALAPANYAG,1011,NaN,NaN,333,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,61809499,12089,20240301,M,K,610000553,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41210,61809500,12088,20240301,M,K,610000561,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41211,61809502,12087,20240301,M,K,610000587,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41212,61809504,12086,20240301,M,K,610000600,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0
41213,61809524,11855,20240301,M,K,610000618,NaN,magi készítési díj,NaN,NaN,...,1.0,Ismeretlen,1,ISMERETLEN,1,NaN,NaN,333,NaN,0

In [131]:
clean_df.columns.size

83

In [129]:
clean_df.drop(axis=1,columns="ADAG_EGYS", inplace=True)

In [88]:
df.to_csv(f"forras/csv/{filename}", sep=';',index=False)